CREATE TABLE public.prng_miejscowosci (
    id_prng character varying NOT NULL,
    hauptname character varying,
    objekttyp character varying,
    objektklasse character varying,
    superobjekt character varying,
    verwaltungsfunktion character varying,
    genitiv character varying,
    adjektiv character varying,
    kommentar character varying,
    quelle character varying,
    unterscheidungselement character varying,
    allg_element character varying,
    ipa_aussprache character varying,
    pol_aussprache character varying,
    lat character varying,
    lon character varying,
    kart_koord_y character varying,
    kart_koord_x character varying,
    aenderungsdatum character varying,
    darstellungsart character varying,
    externes_system character varying,
    id_externes_system character varying,
    id_iip character varying,
    kartenmassstab character varying,
    namensstatus character varying,
    weitere_namen character varying,
    sprachcode_weitere_namen character varying,
    sprache_weitere_namen character varying,
    romaniserte_form_weitere_namen character varying,
    historischer_name character varying,
    sicherer_name character varying,
    kommentar_weiterer_name character varying,
    kommentar_historischer_name character varying,
    kommentar_sicherer_name character varying,
    exonym_fremd character varying,
    exonym_geschrieben character varying,
    exonym_sprache character varying,
    exonym_romanisiert character varying,
    endonym_fremd character varying,
    endonym_geschrieben character varying,
    endonym_sprache character varying,
    endonym_romanisiert character varying,
    staat character varying,
    wojewodschaft character varying,
    powiat character varying,
    gmina character varying,
    id_territ_gliederung character varying,
    erfassungsdatum character varying,
    loeschdatum character varying,
    namespace character varying,
    lat_normalisiert double precision,
    lon_normalisiert double precision,
    coord public.geometry(Point,4326),
    idx integer
);
