CREATE TABLE refs (
    refdbid text,
    refid text,
    db1 text,
    db1id text,
    db2 text,
    db2id text,
    dbpath text,
    path text,
    dbs_in_path text,
    distance integer,
    iteration integer,
    is_inverse_statement boolean,
    stmnt_srcdb text,
    stmnt_src text,
    stmnt1_idx integer,
    stmnt2_idx integer,
    multi_occurence_dbs character varying,
    stmnt1_iteration integer,
    stmnt2_iteration integer,
    db1id_only_one_ref_to_db2 boolean,
    db2id_only_one_ref_to_db1 boolean,
    idx integer,
    preffered_row_idx_for_this_db1_db1id_db2_db2id integer,
    row_number bigint
);
